[package]
name = "component-macro-example"
version = "0.1.0"
edition = "2021"

[dependencies]
summer = { path = "../../summer" }
summer-web = { path = "../../summer-web" }
tokio = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
